version: '3.7'

#para roder os services abaixo
#docker-compose up -d

#para terminar os services abaixo
#docker-compose down 

services:
          
  #spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  db:
    image: mariadb:10.5
    container_name: mudi_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mudi
      MYSQL_USER: root
      MYSQL_PASSWORD: root  
    ports:
      - 3306:3306
    